apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: springpetapp
  name: app-svc
  namespace: aulainfra
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    app: app
    