apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: aulainfra
spec:
  type: ClusterIP
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysqldb-stfs